package packet

const (
	IDConnect = iota
	IDDisconnect
	IDPing
	IDPong
	_
	_
	_
	_
	_
	_
	IDStatus
	IDAuthGrant
	IDAuthToken
	IDServerAuthToken
	IDConnectAccept
	IDPasswordResponse
	IDPasswordAccepted
	IDPasswordRejected
	IDClientReferral
	_
	IDWorldSettings
	IDWorldLoadProgress
	IDWorldLoadFinished
	IDRequestAssets
	IDAssetInitialize
	IDAssetPart
	IDAssetFinalize
	IDRemoveAssets
	IDRequestCommonAssetsRebuild
	IDSetUpdateRate
	IDSetTimeDilation
	IDUpdateFeatures
	IDViewRadius
	IDPlayerOptions
	IDServerTags
	_
	_
	_
	_
	_
	IDUpdateBlockTypes
	IDUpdateBlockHitboxes
	IDUpdateBlockSoundSets
	IDUpdateItemSoundSets
	IDUpdateBlockParticleSets
	IDUpdateBlockBreakingDecals
	IDUpdateBlockSets
	IDUpdateWeathers
	IDUpdateTrails
	IDUpdateParticleSystems
	IDUpdateParticleSpawners
	IDUpdateEntityEffects
	IDUpdateItemPlayerAnimations
	IDUpdateModelvfxs
	IDUpdateItems
	IDUpdateItemQualities
	IDUpdateItemCategories
	IDUpdateItemReticles
	IDUpdateFieldcraftCategories
	IDUpdateResourceTypes
	IDUpdateRecipes
	IDUpdateEnvironments
	IDUpdateAmbienceFX
	IDUpdateFluidFX
	IDUpdateTranslations
	IDUpdateSoundEvents
	IDUpdateInteractions
	IDUpdateRootInteractions
	IDUpdateUnarmedInteractions
	IDTrackOrUpdateObjective
	IDUntrackObjective
	IDUpdateObjectiveTask
	IDUpdateEntityStatTypes
	IDUpdateEntityUIComponents
	IDUpdateHitboxCollisionConfig
	IDUpdateRepulsionConfig
	IDUpdateViewBobbing
	IDUpdateCameraShake
	IDUpdateBlockGroups
	IDUpdateSoundSets
	IDUpdateAudioCategories
	IDUpdateReverbEffects
	IDUpdateEqualizerEffects
	IDUpdateFluids
	IDUpdateTagPatterns
	IDUpdateProjectileConfigs
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	IDSetClientId
	IDSetGameMode
	IDSetMovementStates
	IDSetBlockPlacementOverride
	IDJoinWorld
	IDClientReady
	IDLoadHotbar
	IDSaveHotbar
	IDClientMovement
	IDClientTeleport
	IDUpdateMovementSettings
	IDMouseInteraction
	IDDamageInfo
	IDReticleEvent
	IDDisplayDebug
	IDClearDebugShapes
	IDSyncPlayerPreferences
	IDClientPlaceBlock
	IDUpdateMemoriesFeatureStatus
	IDRemoveMapMarker
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	IDSetChunk
	IDSetChunkHeightmap
	IDSetChunkTintmap
	IDSetChunkEnvironments
	IDUnloadChunk
	IDSetFluids
	_
	_
	_
	IDServerSetBlock
	IDServerSetBlocks
	IDServerSetFluid
	IDServerSetFluids
	IDUpdateBlockDamage
	IDUpdateTimeSettings
	IDUpdateTime
	IDUpdateEditorTimeOverride
	IDClearEditorTimeOverride
	IDUpdateWeather
	IDUpdateEditorWeatherOverride
	IDUpdateEnvironmentMusic
	IDSpawnParticleSystem
	IDSpawnBlockParticleSystem
	IDPlaySoundEvent2D
	IDPlaySoundEvent3D
	IDPlaySoundEventEntity
	IDUpdateSleepState
	IDSetPaused
	IDServerSetPaused
	IDSetEntitySeed
	IDEntityUpdates
	IDPlayAnimation
	IDChangeVelocity
	IDApplyKnockback
	IDSpawnModelParticles
	IDMountMovement
	_
	_
	_
	IDUpdatePlayerInventory
	IDSetCreativeItem
	IDDropCreativeItem
	IDSmartGiveCreativeItem
	IDDropItemStack
	IDMoveItemStack
	IDSmartMoveItemStack
	IDSetActiveSlot
	IDSwitchHotbarBlockSet
	IDInventoryAction
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	IDOpenWindow
	IDUpdateWindow
	IDCloseWindow
	IDSendWindowAction
	IDClientOpenWindow
	_
	_
	_
	_
	_
	IDServerMessage
	IDChatMessage
	IDNotification
	IDKillFeedMessage
	IDShowEventTitle
	IDHideEventTitle
	IDSetPage
	IDCustomHud
	IDCustomPage
	IDCustomPageEvent
	_
	_
	IDEditorBlocksChange
	IDServerInfo
	IDAddToServerPlayerList
	IDRemoveFromServerPlayerList
	IDUpdateServerPlayerList
	IDUpdateServerPlayerListPing
	IDUpdateKnownRecipes
	IDUpdatePortal
	IDUpdateVisibleHudComponents
	IDResetUserInterfaceState
	IDUpdateLanguage
	IDWorldSavingStatus
	IDOpenChatWithCommand
	_
	_
	_
	_
	_
	IDUpdateWorldMapSettings
	IDUpdateWorldMap
	IDClearWorldMap
	IDUpdateWorldMapVisible
	IDTeleportToWorldMapMarker
	IDTeleportToWorldMapPosition
	_
	_
	_
	_
	IDRequestServerAccess
	IDUpdateServerAccess
	IDSetServerAccess
	_
	_
	_
	_
	_
	_
	_
	IDRequestMachinimaActorModel
	IDSetMachinimaActorModel
	IDUpdateMachinimaScene
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	IDSetServerCamera
	IDCameraShakeEffect
	IDRequestFlyCameraMode
	IDSetFlyCameraMode
	_
	_
	_
	_
	_
	_
	IDSyncInteractionChains
	IDCancelInteractionChain
	IDPlayInteractionFor
	IDMountNPC
	IDDismountNPC
	_
	_
	_
	_
	_
	IDFailureReply
	IDSuccessReply
	IDAssetEditorInitialize
	IDAssetEditorAuthorization
	IDAssetEditorCapabilities
	IDAssetEditorSetupSchemas
	IDAssetEditorSetupAssetTypes
	IDAssetEditorCreateDirectory
	IDAssetEditorDeleteDirectory
	IDAssetEditorRenameDirectory
	IDAssetEditorFetchAsset
	IDAssetEditorFetchJsonAssetWithParents
	IDAssetEditorFetchAssetReply
	IDAssetEditorFetchJsonAssetWithParentsReply
	IDAssetEditorAssetPackSetup
	IDAssetEditorUpdateAssetPack
	IDAssetEditorCreateAssetPack
	IDAssetEditorDeleteAssetPack
	IDAssetEditorEnableAssetPack
	IDAssetEditorAssetListSetup
	IDAssetEditorAssetListUpdate
	IDAssetEditorRequestChildrenList
	IDAssetEditorRequestChildrenListReply
	IDAssetEditorUpdateJsonAsset
	IDAssetEditorUpdateAsset
	IDAssetEditorJsonAssetUpdated
	IDAssetEditorAssetUpdated
	IDAssetEditorCreateAsset
	IDAssetEditorRenameAsset
	IDAssetEditorDeleteAsset
	IDAssetEditorDiscardChanges
	IDAssetEditorFetchAutoCompleteData
	IDAssetEditorFetchAutoCompleteDataReply
	IDAssetEditorRequestDataset
	IDAssetEditorRequestDatasetReply
	IDAssetEditorActivateButton
	IDAssetEditorSelectAsset
	IDAssetEditorPopupNotification
	IDAssetEditorFetchLastModifiedAssets
	IDAssetEditorLastModifiedAssets
	IDAssetEditorModifiedAssetsCount
	IDAssetEditorSubscribeModifiedAssetsChanges
	IDAssetEditorExportAssets
	IDAssetEditorExportAssetInitialize
	IDAssetEditorExportAssetPart
	IDAssetEditorExportAssetFinalize
	IDAssetEditorExportDeleteAssets
	IDAssetEditorExportComplete
	IDAssetEditorRebuildCaches
	IDAssetEditorUndoChanges
	IDAssetEditorRedoChanges
	IDAssetEditorUndoRedoReply
	IDAssetEditorSetGameTime
	IDAssetEditorUpdateSecondsPerGameDay
	IDAssetEditorUpdateWeatherPreviewLock
	IDAssetEditorUpdateModelPreview
	_
	_
	_
	_
	IDUpdateSunSettings
	IDUpdatePostFxSettings
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	IDBuilderToolArgUpdate
	IDBuilderToolEntityAction
	IDBuilderToolSetEntityTransform
	IDBuilderToolExtrudeAction
	IDBuilderToolStackArea
	IDBuilderToolSelectionTransform
	IDBuilderToolRotateClipboard
	IDBuilderToolPasteClipboard
	IDBuilderToolSetTransformationModeState
	IDBuilderToolSelectionUpdate
	IDBuilderToolSelectionToolAskForClipboard
	IDBuilderToolSelectionToolReplyWithClipboard
	IDBuilderToolGeneralAction
	IDBuilderToolOnUseInteraction
	IDBuilderToolLineAction
	IDBuilderToolShowAnchor
	IDBuilderToolHideAnchors
	IDPrefabUnselectPrefab
	IDBuilderToolsSetSoundSet
	IDBuilderToolLaserPointer
	IDBuilderToolSetEntityScale
	IDBuilderToolSetEntityPickupEnabled
	IDBuilderToolSetEntityLight
	IDBuilderToolSetNPCDebug
)
